const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');
const app = express();
const server = http.createServer(app);
const io = new Server(server);
app.use(express.static(path.join(__dirname, 'public')));
const CANVAS_WIDTH = 900, CANVAS_HEIGHT = 650, rooms = new Map();
class Player { constructor(id, name) { this.id = id; this.name = name; this.x = CANVAS_WIDTH / 2; this.y = CANVAS_HEIGHT - 80; this.hp = 100; this.score = 0; this.color = `hsl(${Math.random() * 360}, 100%, 60%)`; this.lastShot = 0; } }
const ENEMY_TYPES = [{hp: 25, speed: 3.5, size: 25, color: '#ff3366', score: 100, bulletRate: 0.01}, {hp: 60, speed: 2.5, size: 35, color: '#ff6633', score: 250, bulletRate: 0.015}, {hp: 120, speed: 1.8, size: 45, color: '#ff0000', score: 500, bulletRate: 0.02}, {hp: 200, speed: 2, size: 55, color: '#ff00ff', score: 800, bulletRate: 0.025}];
const BOSS_TYPES = [{name: '咸鱼王', hp: 2000, speed: 1, size: 80, color: '#ff0000', score: 5000, pattern: 'spread'}, {name: '垃圾怪', hp: 3500, speed: 0.8, size: 100, color: '#ff6600', score: 8000, pattern: 'aim'}, {name: '天赫本体', hp: 5000, speed: 1.2, size: 120, color: '#00ffff', score: 15000, pattern: 'chaos'}];
io.on('connection', (socket) => { console.log('玩家连接:', socket.id); let currentRoom = null, player = null;
socket.on('createRoom', (roomName, playerName, callback) => { if (rooms.has(roomName)) { callback({success: false, message: '房间已存在'}); return; } const room = createRoom(roomName); player = new Player(socket.id, playerName); room.players.set(socket.id, player); rooms.set(roomName, room); currentRoom = roomName; socket.join(roomName); callback({success: true, room: roomName, playerId: socket.id}); });
socket.on('joinRoom', (roomName, playerName, callback) => { const room = rooms.get(roomName); if (!room) {callback({success: false, message: '房间不存在'}); return;} if (room.players.size >= 6) {callback({success: false, message: '房间已满'}); return;} if (room.gameStarted) {callback({success: false, message: '游戏已开始'}); return;} player = new Player(socket.id, playerName); room.players.set(socket.id, player); currentRoom = roomName; socket.join(roomName); socket.to(roomName).emit('playerJoined', player); callback({success: true, room: roomName, playerId: socket.id}); });
socket.on('startGame', (callback) => { if (!currentRoom || !player) return; const room = rooms.get(currentRoom); if (!room) return; const host = Array.from(room.players.values())[0]; if (host.id !== socket.id) {callback({success: false, message: '只有房主可以开始'}); return;} startGame(room); io.to(currentRoom).emit('gameStart'); callback({success: true}); });
socket.on('input', (data) => { if (!currentRoom || !player) return; const room = rooms.get(currentRoom); if (!room || !room.gameStarted) return; player.x = Math.max(25, Math.min(CANVAS_WIDTH - 25, data.x)); player.y = Math.max(30, Math.min(CANVAS_HEIGHT - 30, data.y)); if (data.shooting) { const now = Date.now(); if (now - player.lastShot > 80) { player.lastShot = now; room.bullets.push({x: player.x, y: player.y - 25, vx: 0, vy: -18, damage: 15, color: player.color, isLaser: false, playerId: player.id}); if (player.score > 2000) { room.bullets.push({x: player.x - 15, y: player.y - 15, vx: -1, vy: -16, damage: 10, color: player.color, playerId: player.id}); room.bullets.push({x: player.x + 15, y: player.y - 15, vx: 1, vy: -16, damage: 10, color: player.color, playerId: player.id}); } if (player.score > 5000) { room.bullets.push({x: player.x, y: player.y - 20, vx: 0, vy: -25, damage: 5, color: '#00ffff', isLaser: true, playerId: player.id}); } } } socket.to(currentRoom).emit('playerMove', {id: socket.id, x: player.x, y: player.y}); });
socket.on('disconnect', () => { if (!currentRoom) return; const room = rooms.get(currentRoom); if (!room) return; room.players.delete(socket.id); socket.to(currentRoom).emit('playerLeft', socket.id); if (room.players.size === 0) {rooms.delete(currentRoom);} else if (room.gameStarted) { room.gameStarted = false; io.to(currentRoom).emit('gameEnded', '房主离开'); } }); });
function createRoom(name) { return {name, players: new Map(), gameStarted: false, wave: 1, enemies: [], bullets: [], enemyBullets: [], spawnTimer: 0, boss: null}; }
function startGame(room) { room.gameStarted = true; room.wave = 1; room.enemies = []; room.bullets = []; room.enemyBullets = []; room.spawnTimer = 0; room.boss = null; for (let i = 0; i < 5; i++) room.enemies.push(createEnemy(room.wave)); }
function createEnemy(wave) { const type = ENEMY_TYPES[Math.min(Math.floor(wave / 3), ENEMY_TYPES.length - 1)]; return {id: Math.random().toString(36).substr(2, 9), x: 50 + Math.random() * (CANVAS_WIDTH - 100), y: -50, ...type, maxHp: type.hp, shootTimer: Math.random() * 100}; }
function createBoss(wave) { const type = BOSS_TYPES[Math.min(wave - 1, BOSS_TYPES.length - 1)]; return {id: 'boss_' + Date.now(), x: CANVAS_WIDTH / 2, y: -100, targetY: 100, ...type, hp: type.hp, maxHp: type.hp, shootTimer: 0}; }
function updateBoss(room) { const boss = room.boss; if (!boss) return; if (boss.y < boss.targetY) boss.y += 2; boss.x += Math.sin(Date.now() / 1000) * boss.speed * 2; boss.x = Math.max(boss.size, Math.min(CANVAS_WIDTH - boss.size, boss.x)); boss.shootTimer++; const rate = boss.pattern === 'chaos' ? 20 : (boss.pattern === 'aim' ? 40 : 50); if (boss.shootTimer > rate) { boss.shootTimer = 0; if (boss.pattern === 'spread') { for (let i = -4; i <= 4; i++) room.enemyBullets.push({x: boss.x, y: boss.y + 40, vx: i * 1.5, vy: 5, damage: 15, color: '#ff0000'}); } else if (boss.pattern === 'aim') { const targets = Array.from(room.players.values()).slice(0, 3); targets.forEach((p, i) => { const angle = Math.atan2(p.y - boss.y, p.x - boss.x); setTimeout(() => room.enemyBullets.push({x: boss.x, y: boss.y + 40, vx: Math.cos(angle) * 8, vy: Math.sin(angle) * 8, damage: 20, color: '#ffff00'}), i * 100); }); } else { for (let i = 0; i < 12; i++) { const angle = (Math.PI * 2 / 12) * i + Date.now() / 500; room.enemyBullets.push({x: boss.x, y: boss.y + 40, vx: Math.cos(angle) * 4, vy: Math.sin(angle) * 4, damage: 12, color: i % 2 === 0 ? '#ff00ff' : '#00ffff'}); } } } }
setInterval(() => { rooms.forEach((room, roomName) => { if (!room.gameStarted) return; const totalScore = Array.from(room.players.values()).reduce((s, p) => s + p.score, 0); const newWave = Math.floor(totalScore / 3000) + 1; if (newWave > room.wave) { room.wave = newWave; if (room.wave % 3 === 0 && !room.boss) room.boss = createBoss(room.wave); } if (room.boss) updateBoss(room); else { room.spawnTimer++; if (room.spawnTimer > Math.max(30, 80 - room.wave * 5) && room.enemies.length < 4 + room.wave * 2) { room.enemies.push(createEnemy(room.wave)); room.spawnTimer = 0; } } room.enemies.forEach(e => { e.y += e.speed; e.shootTimer++; if (e.shootTimer > 100 / e.bulletRate) { e.shootTimer = 0; const p = getNearest(room, e.x, e.y); if (p) { const a = Math.atan2(p.y - e.y, p.x - e.x); room.enemyBullets.push({x: e.x, y: e.y + e.size / 2, vx: Math.cos(a) * 5, vy: Math.sin(a) * 5, damage: 10, color: e.color}); } } }); room.enemies = room.enemies.filter(e => e.y < CANVAS_HEIGHT + 50); room.bullets = room.bullets.filter(b => { b.y += b.vy; b.x += b.vx || 0; room.enemies.forEach(e => { if (check(b, e)) { e.hp -= b.damage; b.hit = true; } }); if (room.boss && check(b, room.boss)) { room.boss.hp -= b.damage; b.hit = true; } return b.y > -30 && !b.hit; }); room.enemies = room.enemies.filter(e => { if (e.hp <= 0) { const k = room.bullets.find(b => b.playerId); if (k) { const p = room.players.get(k.playerId); if (p) p.score += e.score; } return false; } return true; }); if (room.boss && room.boss.hp <= 0) { room.players.forEach(p => p.score += room.boss.score); room.boss = null; } room.enemyBullets = room.enemyBullets.filter(b => { b.x += b.vx; b.y += b.vy; room.players.forEach(p => { if (Math.abs(b.x - p.x) < 20 && Math.abs(b.y - p.y) < 25) { p.hp -= b.damage; b.hit = true; } }); return b.y < CANVAS_HEIGHT + 20 && b.x > 0 && b.x < CANVAS_WIDTH && !b.hit; }); room.players.forEach((p, id) => { if (p.hp <= 0) { io.to(id).emit('died'); room.players.delete(id); } }); if (totalScore >= 15000 && room.wave >= 5) { room.gameStarted = false; io.to(roomName).emit('gameEnded', '🎉 恭喜通关!'); } io.to(roomName).emit('gameState', {players: Array.from(room.players.values()).map(p => ({id: p.id, name: p.name, x: p.x, y: p.y, hp: p.hp, score: p.score, color: p.color})), enemies: room.enemies, bullets: room.bullets, enemyBullets: room.enemyBullets, wave: room.wave}); }); }, 1000 / 60);
function getNearest(room, x, y) { let n = null, d = Infinity; room.players.forEach(p => { const dist = Math.sqrt((p.x - x) ** 2 + (p.y - y) ** 2); if (dist < d) { d = dist; n = p; } }); return n; }
function check(b, e) { return Math.sqrt((b.x - e.x) ** 2 + (b.y - e.y) ** 2) < e.size; }
const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`⚡ 天赫气死你 - 服务器 http://localhost:${PORT}`));
